### ISSUE TITLE
Example, please.

### ISSUE THREAD

**Issue by andreluisos** [RobbertH/scrcpy-opencv#1]
Interesting. Could you give an example, please?

**Comment by RobbertH** [comment]
Hi @andreluisos , I'm sorry for replying so late, I hadn't noticed your message.
If you are still interested in an example, you can read [my blog post](https://robberthofman.com/projects/2020/03/30/hacking-scrcpy-to-win-fb-soccer-game/). 
If you mean an example on how to use this software, please let me know in a reply on this issue.
