### ISSUE TITLE
Open CV dependency

### ISSUE THREAD

**Issue by mlghty** [RobbertH/scrcpy-opencv#2]
In your blog post you mention "Then, after fiddling some more with meson and installing OpenCV the right way, I was able to call OpenCV from some function in scrcpy that would update every frame.", how did you install OpenCV, I've been trying to install it on Debian but it doesn't seem to be recognized when I try to compile it.

**Comment by RobbertH** [comment]
I followed this tutorial:
https://docs.opencv.org/4.2.0/d7/d9f/tutorial_linux_install.html

**Comment by RobbertH** [comment]
Hey @the-mighty-fall, I did a build on a fresh Ubuntu 20.04 install, keeping track of dependencies along the way.
I updated the [README](https://github.com/RobbertH/scrcpy-opencv/blob/master/README.md#building-opencv), so if you could follow those steps, OpenCV should install and meson should be able to find it.

**Comment by mlghty** [comment]
> Hey @the-mighty-fall, I did a build on a fresh Ubuntu 20.04 install, keeping track of dependencies along the way.
> I updated the [README](https://github.com/RobbertH/scrcpy-opencv/blob/master/README.md#building-opencv), so if you could follow those steps, OpenCV should install and meson should be able to find it.

Thank's @RobbertH I gave up trying to build it on Debian, but successfully built on Ubuntu 20.04 following the readme, Thank you.
